baseURL = "https://blog.mid3.org/"
languageCode = "en-us"
title = "Illiterate's blog"
theme = "hugo-ivy"
publishDir = "docs"

[[menu.main]]
   name       = "首页"
   url        = "/"
   weight     = 1
[[menu.main]]
   identifier = "blog"
   name       = "日志"
   url        = "/posts"
   weight     = 2
 [[menu.main]]
   name       = "分类"
   identifier = "categories"
   url        = "/categories/"
   weight     = 3
 [[menu.main]]
   identifier = "tags"
   name       = "标签"
   url        = "/tags/"
   weight     = 4
 [[menu.main]]
   identifier = "about"
   name       = "关于"
   url        = "about/"
   weight     = 5

[params] 
  description= "Personal website of illiterate"
  footer = "&copy; [illiterate](/) 2021 - 2025"
[params.logo]
  url = "BWcats.PNG" 
  width = 50
  height = 50
  alt = "Logo"

[[params.social]]
         name = "email"
         url  = "mailto:shengyc@gmail.com"
[[params.social]]
         name = "github"
         url  = "https://github.com/illiterater"